log_analytics_workspace_name = "IacDemoWorkspace"
log_analytics_retention_days = 30
solution_plan_map = {
    ContainerInsights= {
      product   = "OMSGallery/ContainerInsights"
      publisher = "Microsoft"
    }
  }

location = "uksouth"
resource_group_name = "apfniacdemo"
hub_vnet_name = "HubVNet"
hub_address_space = ["10.1.0.0/16"]
hub_firewall_subnet_address_prefix = ["10.1.0.0/24"]
hub_bastion_subnet_address_prefix = ["10.1.1.0/24"]
aks_vnet_name = "AksVNet"
aks_vnet_address_space =  ["10.0.0.0/16"]
vm_subnet_name = "VmSubnet"
vm_subnet_address_prefix = ["10.0.48.0/20"]
aks_cluster_name = "IacDemoCluster" 
role_based_access_control_enabled = true
automatic_channel_upgrade = "stable"
admin_group_object_ids = []
azure_rbac_enabled = true
sku_tier = "Free"
kubernetes_version = "1.25.0"
default_node_pool_vm_size = "Standard_F8s_v2"
default_node_pool_availability_zones = ["1", "2", "3"]
network_dns_service_ip = "10.2.0.10"
network_service_cidr = "10.2.0.0/24"
network_plugin = "azure"
pod_subnet_name = "PodSubnet"
pod_subnet_address_prefix =  ["10.0.32.0/20"]
default_node_pool_name = "system"
default_node_pool_subnet_name = "SystemSubnet"
default_node_pool_subnet_address_prefix = ["10.0.0.0/20"]
default_node_pool_enable_auto_scaling = true
default_node_pool_enable_host_encryption = true
default_node_pool_enable_node_public_ip = false
default_node_pool_max_pods = 50
default_node_pool_node_labels = {}
default_node_pool_node_taints =[]
default_node_pool_os_disk_type = "Ephemeral"
default_node_pool_max_count = 10
default_node_pool_min_count = 3
default_node_pool_node_count = 3
additional_node_pool_subnet_name = "UserSubnet"
additional_node_pool_subnet_address_prefix = ["10.0.16.0/20"]
additional_node_pool_name = "user"
additional_node_pool_vm_size = "Standard_F8s_v2"
additional_node_pool_availability_zones = ["1", "2", "3"]
additional_node_pool_enable_auto_scaling = true
additional_node_pool_enable_host_encryption = true
additional_node_pool_enable_node_public_ip = false
additional_node_pool_max_pods = 50
additional_node_pool_mode = "User"
additional_node_pool_node_labels = {}
additional_node_pool_node_taints = ["CriticalAddonsOnly=true:NoSchedule"]
additional_node_pool_os_disk_type = "Ephemeral"
additional_node_pool_os_type = "Linux"
additional_node_pool_priority = "Regular"
additional_node_pool_max_count = 10
additional_node_pool_min_count = 3
additional_node_pool_node_count = 3
domain_name_label = "iactestvm"
firewall_name = "IacFirewall"
firewall_sku_name = "AZFW_VNet"
firewall_sku_tier = "Standard"
firewall_threat_intel_mode = "Alert"
firewall_zones = ["1", "2", "3"]
vm_name = "TestIACVM"
vm_public_ip = false
vm_size = "Standard_DS1_v2"
vm_os_disk_storage_account_type = "Premium_LRS"
vm_os_disk_image =  {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2" 
    version   = "latest"
  }
storage_account_kind = "StorageV2"
storage_account_tier = "Standard"
acr_name = "IacACR"
acr_sku = "Premium"
acr_admin_enabled = true
acr_georeplication_locations = []
tags =  default     = {
    createdWith = "Terraform",
    environment = "Dev"
  }
bastion_host_name = "IacBastionHost"
storage_account_replication_type = "LRS"
key_vault_name = "IacAKSKeyVault"
key_vault_sku_name = "standard"
key_vault_enabled_for_deployment = true
key_vault_enabled_for_disk_encryption = true
key_vault_enabled_for_template_deployment = true
key_vault_enable_rbac_authorization = true
key_vault_purge_protection_enabled = true
key_vault_soft_delete_retention_days = 30
key_vault_bypass = "AzureServices"
key_vault_default_action = "Allow"
admin_username = "azadmin"
ssh_public_key = ""
script_storage_account_name = "scriptstorageacc"
script_storage_account_key = "scriptstoragekey"
container_name = "scriptstoragecont"
script_name = "configure-jumpbox-vm.sh"
keda_enabled = true
vertical_pod_autoscaler_enabled = true
workload_identity_enabled = true
oidc_issuer_enabled = true
open_service_mesh_enabled = true
image_cleaner_enabled = true
azure_policy_enabled = true
http_application_routing_enabled = false